import { weightedTargetsColumn } from "../constants/weightedTargets";

export const materialOptimization: weightedTargetsColumn = {
    rows: [
        {target: 0, weight: undefined},
        {target: 5, weight: undefined},
        {target: 10, weight: undefined},
        {target: 15, weight: undefined},
        {target: 20, weight: '900'},
        {target: 25, weight: '800'},
        {target: 30, weight: '700'},
        {target: 35, weight: '600'},
        {target: 40, weight: '500'},
        {target: 45, weight: undefined},
        {target: 50, weight: '400'},
        {target: 55, weight: '300'},
        {target: 60, weight: undefined},
        {target: 65, weight: undefined},
        {target: 70, weight: '200'},
        {target: 75, weight: undefined},
        {target: 80, weight: undefined},
        {target: 85, weight: '100'},
        {target: 90, weight: undefined},
        {target: 95, weight: '50'},
        {target: 97.5, weight: undefined},
        {target: 100, weight: undefined},
    ],
    neutrals: [
        {target: 0, weight: undefined},
        {target: 5, weight: undefined},
        {target: 10, weight: undefined},
        {target: 15, weight: '900'},
        {target: 20, weight: undefined},
        {target: 25, weight: '800'},
        {target: 30, weight: '700'},
        {target: 35, weight: undefined},
        {target: 40, weight: '600'},
        {target: 45, weight: '500'},
        {target: 50, weight: '400'},
        {target: 55, weight: undefined},
        {target: 60, weight: '300'},
        {target: 65, weight: undefined},
        {target: 70, weight: undefined},
        {target: 75, weight: '200'},
        {target: 80, weight: undefined},
        {target: 85, weight: '100'},
        {target: 90, weight: undefined},
        {target: 95, weight: '50'},
        {target: 97.5, weight: undefined},
        {target: 100, weight: undefined},
    ],
};